// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1KN4lmI8mGzae_O0isf5tXS-dyqcoTmc',
    appId: '1:304726943500:web:733e1cd06ed919a03c4b29',
    messagingSenderId: '304726943500',
    projectId: 'instar-426c1',
    authDomain: 'instar-426c1.firebaseapp.com',
    storageBucket: 'instar-426c1.appspot.com',
    measurementId: 'G-1WY2D1RGVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiAArmd-YiH6_eh2fx1OjOTq88lBShMaY',
    appId: '1:304726943500:android:621beb883206aa673c4b29',
    messagingSenderId: '304726943500',
    projectId: 'instar-426c1',
    storageBucket: 'instar-426c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTXtH38bVfcWN6rpGDW-JhrhdY6TX_cvs',
    appId: '1:304726943500:ios:43a263a31dbb40b33c4b29',
    messagingSenderId: '304726943500',
    projectId: 'instar-426c1',
    storageBucket: 'instar-426c1.appspot.com',
    iosBundleId: 'com.example.dogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTXtH38bVfcWN6rpGDW-JhrhdY6TX_cvs',
    appId: '1:304726943500:ios:43a263a31dbb40b33c4b29',
    messagingSenderId: '304726943500',
    projectId: 'instar-426c1',
    storageBucket: 'instar-426c1.appspot.com',
    iosBundleId: 'com.example.dogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1KN4lmI8mGzae_O0isf5tXS-dyqcoTmc',
    appId: '1:304726943500:web:b1810ca073307ccd3c4b29',
    messagingSenderId: '304726943500',
    projectId: 'instar-426c1',
    authDomain: 'instar-426c1.firebaseapp.com',
    storageBucket: 'instar-426c1.appspot.com',
    measurementId: 'G-GP2ZBEH6B1',
  );
}
